function required(selector) {
  const element = document.querySelector(selector);
  if (!element) throw new Error(`Required UI element not found: ${selector}`);
  return element;
}

function all(selector) {
  return [...document.querySelectorAll(selector)];
}

export function getElements() {
  return Object.freeze({
    machine: required("#machine"),
    machineTitle: required("#machineTitle"),
    machineSubtitle: required("#machineSubtitle"),
    rosterTitle: required("#rosterTitle"),
    modeButtons: all("[data-mode]"),
    themeButtons: all("[data-theme-choice]"),
    guideButton: required("#guideButton"),
    onboarding: required("#onboarding"),
    onboardingSteps: all("[data-onboarding-step]"),
    onboardingProgress: all("[data-progress-step]"),
    onboardingNext: all("[data-onboarding-next]"),
    onboardingBack: all("[data-onboarding-back]"),
    onboardingSkip: all("[data-skip-onboarding]"),
    onboardingModes: all("[data-onboarding-mode]"),
    onboardingThemes: all("[data-onboarding-theme]"),
    firstSignalButton: required("#firstSignalButton"),
    firstSignalPattern: required("#firstSignalPattern"),
    firstSignalState: required("#firstSignalState"),
    finishOnboarding: required("#finishOnboarding"),
    speedPicker: required("#speedPicker"),
    speedTrigger: required("#speedTrigger"),
    speedMenu: required("#speedMenu"),
    speedValue: required("#speedValue"),
    speedMeta: required("#speedMeta"),
    difficultyOptions: all("[data-difficulty]"),
    coachMode: required("#coachMode"),
    coachTitle: required("#coachTitle"),
    coachSteps: required("#coachSteps"),
    speedStat: required("#speedStat"),
    accuracyStat: required("#accuracyStat"),
    streakStat: required("#streakStat"),
    sessionScore: required("#sessionScore"),
    bestScore: required("#bestScore"),
    roster: required("#roster"),
    sprintPanel: required("#sprintPanel"),
    clock: required("#clock"),
    sprintScore: required("#sprintScore"),
    timeTrack: required(".time-track"),
    timeBar: required("#timeBar"),
    learnView: required("#learnView"),
    practiceView: required("#practiceView"),
    lessonStep: required("#lessonStep"),
    lessonPatternText: required("#lessonPatternText"),
    lessonLetter: required("#lessonLetter"),
    lessonSignal: required("#lessonSignal"),
    lessonSpoken: required("#lessonSpoken"),
    lessonNote: required("#lessonNote"),
    previousLesson: required("#previousLesson"),
    hearLesson: required("#hearLesson"),
    nextLesson: required("#nextLesson"),
    statusLine: required("#statusLine"),
    signalButton: required("#signalButton"),
    signalText: required("#signalText"),
    signalBars: required("#signalBars"),
    typedAnswer: required("#typedAnswer"),
    replayButton: required("#replayButton"),
    mainAction: required("#mainAction"),
    answerDeck: required("#answerDeck"),
    answerGrid: required("#answerGrid"),
    footerMode: required("#footerMode"),
    footerResult: required("#footerResult"),
    answerHint: required("#answerHint"),
    signalLab: required("#signalLab"),
    labTabs: all("[data-lab-view]"),
    labPanels: all("[data-lab-panel]"),
    profileStatus: required("#profileStatus"),
    labAttemptSummary: required("#labAttemptSummary"),
    mirrorTargetLabel: required("#mirrorTargetLabel"),
    mirrorReplay: required("#mirrorReplay"),
    mirrorSequence: required("#mirrorSequence"),
    mirrorPad: required("#mirrorPad"),
    mirrorClear: required("#mirrorClear"),
    mirrorCheck: required("#mirrorCheck"),
    mirrorResult: required("#mirrorResult"),
    fingerprintSummary: required("#fingerprintSummary"),
    fingerprintStart: required("#fingerprintStart"),
    fingerprintReset: required("#fingerprintReset"),
    fingerprintEmpty: required("#fingerprintEmpty"),
    fingerprintProgress: required("#fingerprintProgress"),
    fingerprintTable: required("#fingerprintTable"),
    fingerprintRows: required("#fingerprintRows"),
    clinicEmpty: required("#clinicEmpty"),
    clinicReady: required("#clinicReady"),
    clinicProgressBar: required("#clinicProgressBar"),
    clinicProgressText: required("#clinicProgressText"),
    clinicStartDrill: required("#clinicStartDrill"),
    clinicTargetLetter: required("#clinicTargetLetter"),
    clinicTargetPattern: required("#clinicTargetPattern"),
    clinicAnswerLetter: required("#clinicAnswerLetter"),
    clinicAnswerPattern: required("#clinicAnswerPattern"),
    clinicInsight: required("#clinicInsight"),
    clinicPractice: required("#clinicPractice"),
    clinicExit: required("#clinicExit"),
    liveStatus: required("#liveStatus"),
  });
}
